### ISSUE TITLE
As a user, I would like to have the output in .json as well.

### ISSUE THREAD

**Issue by s4pu** [bptlab/scylla#18] opened 2018-03-11 17:11 UTC

**Comment by s4pu** [comment] 2018-03-11 17:20
We were able to create a .json file from the .xml file in the scylla-UI application, so this was not really an issue anymore.

**Comment by LeonBein** [comment] 2021-01-15 10:53
I will close this issue, as the issue is outdated and there seems to be no demand.

**Closed by LeonBein** 2021-01-15 10:53 UTC
Labels: wontfix
